summary: XML-based font configuration tools
webpage: https://wiki.freedesktop.org/www/Software/fontconfig
version: 2.15.0
bin-url: https://github.com/leleliu008/uppm-package-repository-macos-12.0-arm64/releases/download/2024.05.31/fontconfig-2.15.0-macos-12.0-arm64.tar.xz
bin-sha: 7024cbcf07b28e829ba212f60f827f859623ec380a7a672438555ae828896c03
