summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-macos12.0-arm64/releases/download/2023.04.06/pkg-config-0.29.2-macos12.0-arm64.tar.xz
bin-sha: 0b95f9a9712842d916ba3d1ecff39d62932a4772e2958fd8de3585c6779f5b7d
